# Generated by Django 6.0.6 on 2026-07-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("file_path", models.CharField(max_length=255)),
                ("target_column", models.CharField(max_length=100)),
                ("nl_prompt", models.TextField()),
                ("replacement_value", models.CharField(max_length=255)),
                ("result_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
