# Generated by Django 6.0.6 on 2026-07-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processingjob',
            old_name='nl_prompt',
            new_name='prompt',
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='file_path',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='replacement_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='target_column',
            field=models.CharField(max_length=255),
        ),
    ]
