# Generated by Django 6.0.6 on 2026-07-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_nl_prompt_processingjob_prompt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processingjob',
            old_name='file_path',
            new_name='file',
        ),
    ]
