# Generated by Django 6.0.6 on 2026-07-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_file_path_processingjob_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingjob',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='processingjob',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='processingjob',
            name='result_data',
        ),
        migrations.RemoveField(
            model_name='processingjob',
            name='updated_at',
        ),
    ]
