# Generated by Django 6.0.6 on 2026-07-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_processingjob_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='result_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
