# Generated by Django 6.0.6 on 2026-07-14 07:55

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_processingjob_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='file',
            field=models.FileField(upload_to=api.models.job_directory_path),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
