# Generated by Django 6.0.6 on 2026-07-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_processingjob_file_alter_processingjob_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='target_column',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
