# Generated by Django 6.0.6 on 2026-07-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_processingjob_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='columns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
